### ISSUE TITLE
arkOS OSX installer fails

### ISSUE THREAD

**Issue by erje** [arkOScloud/arkos-install#10]
Fresh OSX install, SD card recognized with sufficient permissions. Starting arkOS installer fails, yielding OSStatus error -67049. macerror -67049 yields nothing useful. By-hand solution (using dd) works like a charm.

**Comment by peakwinter** [comment]
Hello! This error usually comes about when a user's settings only allows them to use apps that have been signed with a Mac developer key. Have you tried removing this setting and then trying to use the app? To do this, go to System Settings > Security and Privacy and choose "Allow applications downloaded from anywhere."

**Comment by erje** [comment]
Thanks! Updating the settings as you suggested fixed the issue.

**Comment by elimisteve** [comment]
@jacook What do you think about catching that exception and telling users what you told @erje, so users are told how to solve the problem in the context of the installation?

**Comment by peakwinter** [comment]
Unfortunately this is an OS-level error that is caused before the code is executed, so there's no way I can really catch it. It's the error given when an app doesn't pay Apple's extortion fee for signing up for a cert + signing the app file.

**Comment by erje** [comment]
@jacook Since you can't handle the error in the installation, I would at least add a warning/alert for Mac OSX users on the installer download page. I won't be the last person to run into this issue...

**Comment by arturovm** [comment]
I second that motion :)

–A.

**Comment by peakwinter** [comment]
My apologies, I thought it was stated on the page already. I updated the page to show this. Thanks!

**Comment by elimisteve** [comment]
@jacook Which page, exactly?

**Comment by peakwinter** [comment]
https://arkos.io/downloads/
