### ISSUE TITLE
Start arkos-install on arch linux?

### ISSUE THREAD

**Issue by fazo96** [arkOScloud/arkos-install#16]
I googled a bit, didn't find much. I tried finding the dependences needed but it still won't work

installed python2-crypto, python2-netifaces from the official repos but it still says netifaces import can't be found. I can't run the script with python3 and neither with python2.

Somebody has any advices or solutions? I'm not good with python

**Comment by peakwinter** [comment]
Hm, that's odd. Can you try installing it from PIP instead? Remove it first with `sudo pacman -R python2-netifaces` then `sudo pip2 install netifaces`. Thanks

**Comment by fazo96** [comment]
Sorry if I answer so late but I managed to fix it! Installing netifaces from pip did the trick, the one in the repos doesn't work in this scenario.
For future readers: the script must be run as root using `sudo python2 Installer.py` and also the dependences are `python2-crypto python2-pyqt4` and `netifaces` installed from pip2. The pip2 package in Arch Linux is `python2-pip`
