### ISSUE TITLE
[feature] Add "remove" option for setup.py

### ISSUE THREAD

**Issue by Bugsbane** [arkOScloud/arkos-install#18]
I've got an error which prevents genesis from starting (which I reported a bug on already). I'd like to put Genesis back to its default settings by removing it and reinstalling it.

I was rather surprised that there doesn't seem to be any "remove" option for setup.py to go along with the "install" option. Early days, I guess, but it would help with getting genesis up and going again so early adopters like me can help to do more testing and reporting of bugs.

**Comment by peakwinter** [comment]
If you have `python2-pip` installed (which all new SD card images do), you should be able to remove Genesis like this: `sudo pip2 uninstall genesis`

(btw this is the repo for the Installer, which is why I didn't see this right away :))
