### ISSUE TITLE
Syntax error in Installer.py

### ISSUE THREAD

**Issue by wombalton** [arkOScloud/arkos-install#19]
I tried to run the installer (version 0.3.1) and got the following error:

$ ./arkos-install
Traceback (most recent call last):
  File "./arkos-install", line 3, in <module>
    from arkos_install import Installer
  File "/home/champ/Downloads/arkos_install-0.3.1/arkos_install/Installer.py", line 215
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by nadirs** [comment]
It looks like a python 2 vs 3 incompatibility. The syntax `except Exception as e` should maybe be used instead?

**Comment by peakwinter** [comment]
Yes, the installer is not compatible with Python 3 - you'll have to use it with Python 2 at the moment. Thanks

**Comment by wombalton** [comment]
Thanks for the hint. 
Maybe you shout change the shebang to '#!/usr/bin/env python2' 
This worked for me on an archlinux machine. Don't know about other distros.

**Comment by peakwinter** [comment]
@wombalton This probably wouldn't work on non-Arch based systems. Would be fixed with a PKGBUILD for the AUR, which I'll look into for the next version. Thanks
