### ISSUE TITLE
Can't run the installer in Ubuntu 13.10

### ISSUE THREAD

**Issue by amo13** [arkOScloud/arkos-install#21]
Hey, I'm afraid I need some help...
I installed the package with the package installer of ubuntu. Then I tried to run the arkos-installer like any other application, but it says I don't have the rights and I should try to run "sudo Installer.py" instead. So I did that but I only get the message "sudo: Installer.py: command not found". I tried to make that Installer.py executable but nothing changed. I also verified that if I have python installed but it looks so (python and python interpreter 3.3 installed). 
what did I do wrong?

**Comment by peakwinter** [comment]
Hi amo13 - if you are in the same folder as Installer.py, you will actually have to run `sudo ./Installer.py` or `sudo python Installer.py` to get it to work. Also the application is in Python 2.x so make sure you have that installed.

Thanks!

**Comment by amo13** [comment]
Great! The first one did it.
I still have much to learn about using Linux...

Thank you!
