### ISSUE TITLE
Please sign images with OpenPGP and use better hash algorithm

### ISSUE THREAD

**Issue by baldpitter** [arkOScloud/arkos-install#27]
I just downloaded an arkOS image and had the following thoughts concerning the security implications:
1. Security might be improved by signing the images provided on the website using the OpenPGP standard (in order to better prevent MITM attacks). In a second step, the public key could be spreaded via keybase.io and connected to the cznweb twitter account.
2. Furthermore, I recommend switching the hash algorithm from MD5 to something more secure like SHA-256.

Thank you for your great product!

**Comment by elimisteve** [comment]
Hi @baldpitter, was the arkOS link you downloaded via an HTTPS one?  Because that will prevent MITM attacks :-).  (Keybase rocks btw!)

Also, while it's true that MD5 is not suitable for cryptographic purposes, it's still a great choice to ensure file integrity, which I believe is the goal of @peakwinter in this case.

**Comment by baldpitter** [comment]
Hey @elimisteve @peakwinter ,

great that you have switched the hash algorithm to SHA-256!

Since the Linux Mint images got hacked (http://blog.linuxmint.com/?p=2994), I want to emphasize that the arkOS images should be properly signed. Relevant Hacker News thread concerning the issue: https://news.ycombinator.com/item?id=11142986

HTTPS itself is no proper protection against MITM attacks. E.g. every CA my browser trusts could provide me with a compromised arkOS image and the corresponding hash value without me knowing it. Only a proper signing modell can improve this situation.

Furthermore, HTTPS does not help if the server itself got hacked. This happend to Linux Mint. Using HTTPS would not have helped in this case because it does not protect the endpoint.

**Comment by peakwinter** [comment]
Thanks for the input @baldpitter !

Definitely considering adding PGP signatures to the image production process as well. That should come soon. We already sign all of the software packages we distribute on the mirrors via pacman.

Should also be mentioned that our site uses statically-generated HTML pages (so no worries about WordPress/PHP compromise!)

**Comment by peakwinter** [comment]
BTW: signatures are now available for all images on the Downloads page :)
