### ISSUE TITLE
[minor bug] authentication loop if link is in expected directory instead of file itself

### ISSUE THREAD

**Issue by Cathryne** [arkOScloud/arkos-install#9]
Re-installed ArkOS with the installer app on Mac OS X 10.7.5. I had moved the files latest.tar.gz & latest.tar.gz.md5.txt into a sub-folder of /Downloads and put links there instead. The installer kept on going with the "Found package in working directory. Authenticating..."-process, never progressing to writing the data.

**Comment by peakwinter** [comment]
Thanks for reporting this! I'll look into it

**Comment by Cathryne** [comment]
Thanks for fixing :-)
